// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	NameMessage
	WhisperMessage
	WhisperAck
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NameMessage struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *NameMessage) Reset()                    { *m = NameMessage{} }
func (m *NameMessage) String() string            { return proto.CompactTextString(m) }
func (*NameMessage) ProtoMessage()               {}
func (*NameMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NameMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WhisperMessage struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *WhisperMessage) Reset()                    { *m = WhisperMessage{} }
func (m *WhisperMessage) String() string            { return proto.CompactTextString(m) }
func (*WhisperMessage) ProtoMessage()               {}
func (*WhisperMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WhisperMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *WhisperMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type WhisperAck struct {
	Response bool `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
}

func (m *WhisperAck) Reset()                    { *m = WhisperAck{} }
func (m *WhisperAck) String() string            { return proto.CompactTextString(m) }
func (*WhisperAck) ProtoMessage()               {}
func (*WhisperAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WhisperAck) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

func init() {
	proto.RegisterType((*NameMessage)(nil), "service.NameMessage")
	proto.RegisterType((*WhisperMessage)(nil), "service.WhisperMessage")
	proto.RegisterType((*WhisperAck)(nil), "service.WhisperAck")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Name service

type NameClient interface {
	SayName(ctx context.Context, in *NameMessage, opts ...grpc.CallOption) (*NameMessage, error)
}

type nameClient struct {
	cc *grpc.ClientConn
}

func NewNameClient(cc *grpc.ClientConn) NameClient {
	return &nameClient{cc}
}

func (c *nameClient) SayName(ctx context.Context, in *NameMessage, opts ...grpc.CallOption) (*NameMessage, error) {
	out := new(NameMessage)
	err := grpc.Invoke(ctx, "/service.Name/SayName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Name service

type NameServer interface {
	SayName(context.Context, *NameMessage) (*NameMessage, error)
}

func RegisterNameServer(s *grpc.Server, srv NameServer) {
	s.RegisterService(&_Name_serviceDesc, srv)
}

func _Name_SayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServer).SayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Name/SayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServer).SayName(ctx, req.(*NameMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Name_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Name",
	HandlerType: (*NameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayName",
			Handler:    _Name_SayName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// Client API for Whisper service

type WhisperClient interface {
	SendWhisper(ctx context.Context, in *WhisperMessage, opts ...grpc.CallOption) (*WhisperAck, error)
}

type whisperClient struct {
	cc *grpc.ClientConn
}

func NewWhisperClient(cc *grpc.ClientConn) WhisperClient {
	return &whisperClient{cc}
}

func (c *whisperClient) SendWhisper(ctx context.Context, in *WhisperMessage, opts ...grpc.CallOption) (*WhisperAck, error) {
	out := new(WhisperAck)
	err := grpc.Invoke(ctx, "/service.Whisper/SendWhisper", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Whisper service

type WhisperServer interface {
	SendWhisper(context.Context, *WhisperMessage) (*WhisperAck, error)
}

func RegisterWhisperServer(s *grpc.Server, srv WhisperServer) {
	s.RegisterService(&_Whisper_serviceDesc, srv)
}

func _Whisper_SendWhisper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhisperMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServer).SendWhisper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Whisper/SendWhisper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServer).SendWhisper(ctx, req.(*WhisperMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Whisper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Whisper",
	HandlerType: (*WhisperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWhisper",
			Handler:    _Whisper_SendWhisper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x14, 0xb9,
	0xb8, 0xfd, 0x12, 0x73, 0x53, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x1b, 0x2e,
	0xbe, 0xf0, 0x8c, 0xcc, 0xe2, 0x82, 0xd4, 0x22, 0x98, 0x2a, 0x31, 0x2e, 0xb6, 0xe2, 0xfc, 0xd2,
	0xa2, 0x64, 0x98, 0x3a, 0x28, 0x0f, 0xa4, 0x3b, 0x29, 0x3f, 0xa5, 0x52, 0x82, 0x09, 0xa2, 0x1b,
	0xc4, 0x56, 0xd2, 0xe0, 0xe2, 0x82, 0xea, 0x76, 0x4c, 0xce, 0x16, 0x92, 0xe2, 0xe2, 0x28, 0x4a,
	0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x86, 0xe8, 0xe5, 0x08, 0x82, 0xf3, 0x8d, 0xec, 0xb9, 0x58, 0x40,
	0x4e, 0x11, 0x32, 0xe7, 0x62, 0x0f, 0x4e, 0xac, 0x04, 0x33, 0x45, 0xf4, 0x60, 0xce, 0x46, 0x72,
	0xa4, 0x14, 0x56, 0x51, 0x25, 0x06, 0x23, 0x0f, 0x2e, 0x76, 0xa8, 0x55, 0x42, 0xb6, 0x5c, 0xdc,
	0xc1, 0xa9, 0x79, 0x29, 0x30, 0xae, 0x38, 0x5c, 0x07, 0xaa, 0x4f, 0xa4, 0x84, 0xd1, 0x25, 0x1c,
	0x93, 0xb3, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0xa1, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x86,
	0x13, 0x8d, 0x60, 0x36, 0x01, 0x00, 0x00,
}
