// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	WhisperMessage
	WhisperAck
	NodeMessage
	NodeRequestReply
	NodeRequestMessage
	NodeInformMessage
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WhisperMessage struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *WhisperMessage) Reset()                    { *m = WhisperMessage{} }
func (m *WhisperMessage) String() string            { return proto.CompactTextString(m) }
func (*WhisperMessage) ProtoMessage()               {}
func (*WhisperMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WhisperMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *WhisperMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type WhisperAck struct {
	Response bool `protobuf:"varint,1,opt,name=response" json:"response,omitempty"`
}

func (m *WhisperAck) Reset()                    { *m = WhisperAck{} }
func (m *WhisperAck) String() string            { return proto.CompactTextString(m) }
func (*WhisperAck) ProtoMessage()               {}
func (*WhisperAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WhisperAck) GetResponse() bool {
	if m != nil {
		return m.Response
	}
	return false
}

type NodeMessage struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port int32  `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
}

func (m *NodeMessage) Reset()                    { *m = NodeMessage{} }
func (m *NodeMessage) String() string            { return proto.CompactTextString(m) }
func (*NodeMessage) ProtoMessage()               {}
func (*NodeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeMessage) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *NodeMessage) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type NodeRequestReply struct {
	Found    bool         `protobuf:"varint,1,opt,name=found" json:"found,omitempty"`
	Contents *NodeMessage `protobuf:"bytes,2,opt,name=contents" json:"contents,omitempty"`
}

func (m *NodeRequestReply) Reset()                    { *m = NodeRequestReply{} }
func (m *NodeRequestReply) String() string            { return proto.CompactTextString(m) }
func (*NodeRequestReply) ProtoMessage()               {}
func (*NodeRequestReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeRequestReply) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *NodeRequestReply) GetContents() *NodeMessage {
	if m != nil {
		return m.Contents
	}
	return nil
}

type NodeRequestMessage struct {
	Informer *NodeMessage `protobuf:"bytes,1,opt,name=informer" json:"informer,omitempty"`
	Request  string       `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Exclude  []string     `protobuf:"bytes,3,rep,name=exclude" json:"exclude,omitempty"`
}

func (m *NodeRequestMessage) Reset()                    { *m = NodeRequestMessage{} }
func (m *NodeRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*NodeRequestMessage) ProtoMessage()               {}
func (*NodeRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NodeRequestMessage) GetInformer() *NodeMessage {
	if m != nil {
		return m.Informer
	}
	return nil
}

func (m *NodeRequestMessage) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *NodeRequestMessage) GetExclude() []string {
	if m != nil {
		return m.Exclude
	}
	return nil
}

type NodeInformMessage struct {
	Informer *NodeMessage   `protobuf:"bytes,1,opt,name=informer" json:"informer,omitempty"`
	Pool     []*NodeMessage `protobuf:"bytes,2,rep,name=pool" json:"pool,omitempty"`
}

func (m *NodeInformMessage) Reset()                    { *m = NodeInformMessage{} }
func (m *NodeInformMessage) String() string            { return proto.CompactTextString(m) }
func (*NodeInformMessage) ProtoMessage()               {}
func (*NodeInformMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NodeInformMessage) GetInformer() *NodeMessage {
	if m != nil {
		return m.Informer
	}
	return nil
}

func (m *NodeInformMessage) GetPool() []*NodeMessage {
	if m != nil {
		return m.Pool
	}
	return nil
}

func init() {
	proto.RegisterType((*WhisperMessage)(nil), "service.WhisperMessage")
	proto.RegisterType((*WhisperAck)(nil), "service.WhisperAck")
	proto.RegisterType((*NodeMessage)(nil), "service.NodeMessage")
	proto.RegisterType((*NodeRequestReply)(nil), "service.NodeRequestReply")
	proto.RegisterType((*NodeRequestMessage)(nil), "service.NodeRequestMessage")
	proto.RegisterType((*NodeInformMessage)(nil), "service.NodeInformMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Whisper service

type WhisperClient interface {
	SendWhisper(ctx context.Context, in *WhisperMessage, opts ...grpc.CallOption) (*WhisperAck, error)
}

type whisperClient struct {
	cc *grpc.ClientConn
}

func NewWhisperClient(cc *grpc.ClientConn) WhisperClient {
	return &whisperClient{cc}
}

func (c *whisperClient) SendWhisper(ctx context.Context, in *WhisperMessage, opts ...grpc.CallOption) (*WhisperAck, error) {
	out := new(WhisperAck)
	err := grpc.Invoke(ctx, "/service.Whisper/SendWhisper", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Whisper service

type WhisperServer interface {
	SendWhisper(context.Context, *WhisperMessage) (*WhisperAck, error)
}

func RegisterWhisperServer(s *grpc.Server, srv WhisperServer) {
	s.RegisterService(&_Whisper_serviceDesc, srv)
}

func _Whisper_SendWhisper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhisperMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhisperServer).SendWhisper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Whisper/SendWhisper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhisperServer).SendWhisper(ctx, req.(*WhisperMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Whisper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Whisper",
	HandlerType: (*WhisperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendWhisper",
			Handler:    _Whisper_SendWhisper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// Client API for Name service

type NameClient interface {
	SayName(ctx context.Context, in *NodeMessage, opts ...grpc.CallOption) (*NodeMessage, error)
}

type nameClient struct {
	cc *grpc.ClientConn
}

func NewNameClient(cc *grpc.ClientConn) NameClient {
	return &nameClient{cc}
}

func (c *nameClient) SayName(ctx context.Context, in *NodeMessage, opts ...grpc.CallOption) (*NodeMessage, error) {
	out := new(NodeMessage)
	err := grpc.Invoke(ctx, "/service.Name/SayName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Name service

type NameServer interface {
	SayName(context.Context, *NodeMessage) (*NodeMessage, error)
}

func RegisterNameServer(s *grpc.Server, srv NameServer) {
	s.RegisterService(&_Name_serviceDesc, srv)
}

func _Name_SayName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServer).SayName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Name/SayName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServer).SayName(ctx, req.(*NodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Name_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Name",
	HandlerType: (*NameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayName",
			Handler:    _Name_SayName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

// Client API for InformService service

type InformServiceClient interface {
	InformNode(ctx context.Context, in *NodeInformMessage, opts ...grpc.CallOption) (*NodeInformMessage, error)
	RequestNode(ctx context.Context, in *NodeRequestMessage, opts ...grpc.CallOption) (*NodeRequestReply, error)
}

type informServiceClient struct {
	cc *grpc.ClientConn
}

func NewInformServiceClient(cc *grpc.ClientConn) InformServiceClient {
	return &informServiceClient{cc}
}

func (c *informServiceClient) InformNode(ctx context.Context, in *NodeInformMessage, opts ...grpc.CallOption) (*NodeInformMessage, error) {
	out := new(NodeInformMessage)
	err := grpc.Invoke(ctx, "/service.InformService/InformNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *informServiceClient) RequestNode(ctx context.Context, in *NodeRequestMessage, opts ...grpc.CallOption) (*NodeRequestReply, error) {
	out := new(NodeRequestReply)
	err := grpc.Invoke(ctx, "/service.InformService/RequestNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InformService service

type InformServiceServer interface {
	InformNode(context.Context, *NodeInformMessage) (*NodeInformMessage, error)
	RequestNode(context.Context, *NodeRequestMessage) (*NodeRequestReply, error)
}

func RegisterInformServiceServer(s *grpc.Server, srv InformServiceServer) {
	s.RegisterService(&_InformService_serviceDesc, srv)
}

func _InformService_InformNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInformMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformServiceServer).InformNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.InformService/InformNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformServiceServer).InformNode(ctx, req.(*NodeInformMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _InformService_RequestNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformServiceServer).RequestNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.InformService/RequestNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformServiceServer).RequestNode(ctx, req.(*NodeRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _InformService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.InformService",
	HandlerType: (*InformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InformNode",
			Handler:    _InformService_InformNode_Handler,
		},
		{
			MethodName: "RequestNode",
			Handler:    _InformService_RequestNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xb5, 0x31, 0x60, 0x77, 0x2c, 0xaa, 0x76, 0x8b, 0x5a, 0xd7, 0xbd, 0x58, 0x7b, 0xf2, 0x09,
	0x21, 0xf7, 0xd0, 0x4b, 0xab, 0x8a, 0x4b, 0x1b, 0x0e, 0xe1, 0x60, 0x0e, 0x91, 0x72, 0x03, 0x7b,
	0x08, 0x08, 0xf0, 0x3a, 0xbb, 0x76, 0x14, 0xf2, 0x35, 0xf9, 0xd4, 0x68, 0xd7, 0xbb, 0x08, 0x47,
	0x90, 0x43, 0x6e, 0xf3, 0xe6, 0xbd, 0x79, 0xcf, 0xbb, 0xb3, 0x86, 0x81, 0x40, 0xfe, 0xb0, 0xc9,
	0x70, 0x54, 0x72, 0x56, 0x31, 0xe2, 0x6a, 0x48, 0x7f, 0xc3, 0xc7, 0x9b, 0xf5, 0x46, 0x94, 0xc8,
	0xaf, 0x51, 0x88, 0xc5, 0x1d, 0x92, 0xaf, 0xd0, 0x17, 0xac, 0xe6, 0x19, 0x06, 0x76, 0x64, 0xc7,
	0x1f, 0x52, 0x8d, 0x08, 0x81, 0xee, 0x92, 0xe5, 0x87, 0xa0, 0xa3, 0xba, 0xaa, 0xa6, 0x31, 0x80,
	0x9e, 0x9e, 0x64, 0x5b, 0x12, 0x82, 0xc7, 0x51, 0x94, 0xac, 0x10, 0xcd, 0xac, 0x97, 0x1e, 0x31,
	0x9d, 0x82, 0x3f, 0x63, 0x39, 0x9a, 0x10, 0x02, 0xdd, 0x62, 0xb1, 0x37, 0x11, 0xaa, 0x96, 0xbd,
	0x35, 0x13, 0x95, 0x09, 0x90, 0xb5, 0xec, 0x95, 0x8c, 0x57, 0x81, 0x13, 0xd9, 0x71, 0x2f, 0x55,
	0x35, 0xbd, 0x85, 0x4f, 0xd2, 0x2a, 0xc5, 0xfb, 0x1a, 0x45, 0x95, 0x62, 0xb9, 0x3b, 0x90, 0x21,
	0xf4, 0x56, 0xac, 0x2e, 0x72, 0x9d, 0xdb, 0x00, 0x32, 0x06, 0x2f, 0x63, 0x45, 0x85, 0x45, 0x25,
	0x94, 0xab, 0x9f, 0x0c, 0x47, 0xe6, 0x1e, 0x4e, 0xbe, 0x26, 0x3d, 0xaa, 0xe8, 0x13, 0x90, 0x13,
	0x6f, 0xf3, 0xb5, 0x63, 0xf0, 0x36, 0xc5, 0x8a, 0xf1, 0x3d, 0x72, 0x15, 0x70, 0xd1, 0xc7, 0xa8,
	0x48, 0x00, 0x2e, 0x6f, 0x3c, 0xf4, 0x71, 0x0c, 0x94, 0x0c, 0x3e, 0x66, 0xbb, 0x3a, 0xc7, 0xc0,
	0x89, 0x1c, 0xc9, 0x68, 0x48, 0x19, 0x7c, 0x96, 0x66, 0x53, 0xe5, 0xf1, 0xfe, 0xe8, 0x58, 0x5e,
	0x19, 0xdb, 0x05, 0x9d, 0xc8, 0xb9, 0xa8, 0x56, 0x8a, 0xe4, 0x0a, 0x5c, 0xbd, 0x3d, 0xf2, 0x07,
	0xfc, 0x39, 0x16, 0xb9, 0x81, 0xdf, 0x8e, 0x53, 0xed, 0xc7, 0x11, 0x7e, 0x79, 0x4d, 0x4c, 0xb2,
	0x2d, 0xb5, 0x92, 0xbf, 0xd0, 0x9d, 0xc9, 0x15, 0xfe, 0x02, 0x77, 0xbe, 0x38, 0xa8, 0xf2, 0x6c,
	0x70, 0x78, 0xb6, 0x4b, 0xad, 0xe4, 0xd9, 0x86, 0x41, 0x73, 0xf0, 0x79, 0xc3, 0x93, 0x7f, 0x00,
	0x4d, 0x43, 0x0a, 0x49, 0xd8, 0x9a, 0x6b, 0x5d, 0x51, 0xf8, 0x06, 0x47, 0x2d, 0xf2, 0x1f, 0x7c,
	0xbd, 0x4d, 0x65, 0xf4, 0xa3, 0x25, 0x6e, 0xef, 0x39, 0xfc, 0x7e, 0x8e, 0x54, 0x0f, 0x8c, 0x5a,
	0xcb, 0xbe, 0xfa, 0x73, 0x7e, 0xbe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xb9, 0x16, 0x45, 0x4a,
	0x03, 0x00, 0x00,
}
